[book]
title = "알고리즘 모음집"
description = "다양한 알고리즘을 모아 놓고 있습니다."
authors = ["few256"]
language = "ko"

[rust]
edition = "2021"

[build]
build-dir = "book"
create-missing = false

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/few256/algorithms"

[output.html.fold]
enable = true
level = 1

[output.html.print]
enable = false
page-break = true

[output.html.playground]
copyable = true
editable = true
copy-js = true
line-numbers = true
runnable = true

[output.html.search]
enable = true
limit-results = 20
expand = true
copy-js = true
